---
title: "Figures"
author: "Kiri Kuroda"
date: "`r Sys.Date()`"
output:
  html_document:
    css: ../css/style.scss
    md_extensions: -ascii_identifiers
    theme: cerulean
    df_print: default
    chunk_output_type: console
    toc: yes
    toc_float:
      collapsed: false
---

<link rel="stylesheet" href="../js/highlight/styles/monokai.css">
<script src="../js/highlight/highlight.pack.js"></script>
<script>hljs.initHighlightingOnLoad();</script>

<style>
@import url('https://fonts.googleapis.com/css2?family=Montserrat:wght@400;700&display=swap');
</style>

```{r setup, message=FALSE, warning=FALSE}
library(tidyverse)
library(plotrix)
library(emmeans)
library(effectsize)
library(afex)
library(ggmosaic)
library(patchwork)
library(ggsignif)
source("../function/my_functions.R")

df_task <- read_csv("../data/outcomebias_task.csv")
df_participants <- read_csv("../data/outcomebias_participants.csv")
```

# Figure 1

## Figure 1b

```{r}
figure_1b <- df_task %>%
  left_join(df_participants, by = "id") %>%
  group_by(outcome, univ) %>%
  summarise(mean = mean(rating_policy), se = std.error(rating_policy), .groups = "drop") %>%
  ggplot(aes(x = outcome, y = mean, color = univ, shape = univ)) +
  geom_point(size = 2, position = position_dodge(width = 0.4)) +
  geom_errorbar(
    aes(ymin = mean - se, ymax = mean + se),
    width = 0.2, position = position_dodge(width = 0.4)
  ) +
  # geom_vline(aes(xintercept = 4.5), linetype = "dashed") +
  scale_x_discrete(
    limits = c("success", "failure", "control", "inequality", "sure"),
    labels = c("Success", "Failure", "Control", "Inequality", "The sure\npolicy")
  ) +
  scale_y_continuous(breaks = seq(3, 4.5, 0.5), limits = c(3.4, 4.8)) +
  scale_color_manual(
    values = c("#23651c", "#f2a900"),
    labels = c("Hokkaido", "Tokyo")
  ) +
  scale_shape_discrete(labels = c("Hokkaido", "Tokyo")) +
  labs(
    x = "",
    y = "Ratings for the policies",
    color = "University",
    shape = "University"
  ) +
  theme(
    legend.direction = "horizontal",
    legend.position = c(0.5, 0.95),
    legend.title = element_blank()
  )
figure_1b
```

## Figure 1c

```{r}
figure_1c <- df_task %>%
  group_by(outcome) %>%
  summarise(mean = mean(rating_policy), se = std.error(rating_policy), .groups = "drop") %>%
  mutate(
    outcome = fct_recode(
      outcome,
      Success = "success",
      Failure = "failure",
      Control = "control",
      Inequality = "inequality",
      "The sure\npolicy" = "sure"
    ),
    outcome = fct_relevel(outcome, "Success", "Failure", "Control", "Inequality", "The sure\npolicy")
  ) %>%
  ggplot(aes(x = outcome, y = mean)) +
  geom_point() +
  geom_errorbar(aes(ymin = mean - se, ymax = mean + se), width = 0.2) +
  geom_signif(
    y_position = c(4.65, 4.45), xmin = c(1, 4), xmax = c(4, 5),
    annotation = c("p = .004", "p = .005"), tip_length = 0.05,
    size = 0.2, textsize = 3
  ) +
  scale_y_continuous(limits = c(3.4, 4.8), breaks = seq(3, 4.5, 0.5)) +
  labs(
    x = "",
    y = "Ratings for the policies"
  )
figure_1c
```

## Figure 1b + 1c

```{r}
figure_1bc <- (figure_1b / figure_1c) + plot_layout(heights = c(1,1))
figure_1bc
ggsave(
  "../figure/figure_1bc.pdf", figure_1bc, device = cairo_pdf,
  width = 9.25, height = 12, units = "cm"
)
```

# Figure 2

## Figure 2a

```{r}
figure_2a <- df_participants %>%
  mutate(
    distributor = if_else(rating_distributor >= 3, "risky", "sure"),
    recipient = if_else(rating_recipient >= 3, "risky", "sure"),
    preference = case_when(
      distributor == "risky" & recipient == "risky" ~ "1",
      distributor == "sure" & recipient == "sure" ~ "4",
      distributor == "risky" & recipient == "sure" ~ "2",
      distributor == "sure" & recipient == "risky" ~ "3"
    )
  ) %>%
  count(distributor, recipient, preference) %>%
  group_by(distributor, .groups = "drop") %>%
  mutate(
    width = (sum(n) / 251) * 2,
    prop = n / sum(n),
    height = cumsum(prop) - 0.5 * prop
  ) %>%
  ggplot(aes(x = distributor, y = n, fill = fct_rev(preference), width = width)) +
  geom_bar(stat = "identity", position = "fill", color = "white") +
  geom_text(aes(y = height, label = n, color = preference)) +
  scale_x_discrete(expand = c(0, 0), labels = c("Risky", "Sure")) +
  scale_y_continuous(
    expand = c(0, 0),
    breaks = c(0.33, 0.83),
    labels = c("Risky", "Sure")
  ) +
  scale_color_manual(values = c("black", "black", "black", "white")) +
  scale_fill_manual(values = c("#0072b2", "gray", "gray", "orange")) +
  labs(
    x = "Decision makers' distributive choices",
    y = "Receivers' distributive choices",
    tag = "a"
  ) +
  guides(fill = FALSE, color = FALSE) +
  theme(
    axis.line = element_blank(),
    axis.title.y = element_text(size = 8),
    plot.tag = element_text(size = 14)
  )
figure_2a
```

## Figure 2b

```{r}
figure_2b <- df_participants %>%
  mutate(
    distributor = if_else(rating_distributor >= 3, "risky", "sure"),
    recipient = if_else(rating_recipient >= 3, "risky", "sure"),
    preference = case_when(
      distributor == "risky" & recipient == "risky" ~ "1",
      distributor == "sure" & recipient == "sure" ~ "4",
      distributor == "risky" & recipient == "sure" ~ "2",
      distributor == "sure" & recipient == "risky" ~ "3"
    )
  ) %>%
  left_join(df_task, by = "id") %>%
  filter(distributor == recipient) %>%
  mutate(distributor = if_else(distributor == "risky", "Risky", "Sure")) %>%
  group_by(outcome, distributor) %>%
  summarise(
    mean = mean(rating_policy), se = std.error(rating_policy),
    .groups = "drop"
  ) %>%
  mutate(
    outcome = fct_recode(
      outcome,
      Success = "success",
      Failure = "failure",
      Control = "control",
      Inequality = "inequality",
      "The sure\npolicy" = "sure"
    ),
    outcome = fct_relevel(outcome, "Success", "Failure", "Control", "Inequality", "The sure\npolicy")
  ) %>%
  ggplot(aes(x = outcome, y = mean, color = distributor, shape = distributor)) +
  geom_point(size = 2, position = position_dodge(width = 0.4)) +
  geom_errorbar(
    aes(ymin = mean - se, ymax = mean + se),
    width = 0.2, position = position_dodge(width = 0.4)
  ) +
  geom_signif(
    y_position = c(5.3, 5.0, 4.8), xmin = c(1.1, 3.9, 4.9), xmax = c(4.1, 4.1, 5.1),
    annotation = c("p = .070", "p = .003", "p < .001"), tip_length = 0.02,
    size = 0.2, textsize = 3, color = "black"
  ) +
  scale_y_continuous(limits = c(3.3, 5.4)) +
  scale_color_manual(values = c("orange", "#0072b2")) +
  labs(
    x = "",
    y = "Ratings for the policies",
    color = "Types\n(distributive\npreferences)",
    shape = "Types\n(distributive\npreferences)",
    tag = "b"
  ) +
  theme(
    legend.title = element_text(size = 8),
    legend.margin = margin(0,0,0,0)
  )
figure_2b
```

## Figure 2a + 2b

```{r}
figure_2ab <- (figure_2a + figure_2b) + plot_layout(widths = c(1,1.4))
figure_2ab
ggsave(
  "../figure/figure_2ab.pdf", figure_2ab, device = cairo_pdf,
  width = 18.3, height = 6, units = "cm"
)
```